---
title: 'Data Wrangling Exercise 1: Basic Data Manipulation'
author: "Aadrika Singh"
date: "August 14, 2017"
output: html_document
---

# Load data and packages
```{r}
library(dplyr)
library(tidyr)
store <- read.csv("refine_original.csv")
```

#Clean up brand names
```{r}
#transform the values to lowercase
store$company <- tolower(store$company)

#looking at the distinct values in the company column (should ideally be 4)
unique(store$company)

#standardize the values and remove misspellings (using regular expressions)
store$company <- gsub(pattern = "^a[[:alnum:][:space:]]*", replacement = "Akzo", x = store$company)

store$company <- gsub(pattern = "^[p,f][[:alnum:][:space:]]*", replacement = "Philips", x = store$company)

store$company <- gsub(pattern = "^v[[:alnum:][:space:]]*", replacement = "Van Houten", x = store$company)

store$company <- gsub(pattern = "^u[[:alnum:][:space:]]*", replacement = "Unilever", x = store$company)
```

#Separate product code and number
```{r}
store <- separate(data = store, col = Product.code...number, into = c("product_code","product_number"), sep = "-")
```

#Add product categories
```{r}
store$product_category <- ifelse(store$product_code == "p","Smartphone",
                                 ifelse(store$product_code == "v","TV",
                                        ifelse(store$product_code == "x","Laptop",
                                               ifelse(store$product_code == "q","Tablet",
                                                      "Unknown"))))
```

#Add full address for geocoding
```{r}
store <- unite(data = store, col = "full_address", ... = address:country, sep = ", ")

#If address, city, and country variables are to be kept
#store$full_address <- paste(store$address, store$city, store$country, sep = ", ")
```

#Create dummy variables for company
```{r}
store$company_philips <- as.numeric(store$company == "Philips")
store$company_akzo <- as.numeric(store$company == "Akzo")
store$company_van_houten <- as.numeric(store$company == "Van Houten")
store$company_unilever <- as.numeric(store$company == "Unilever")
```

#Create dummy variables for product category
```{r}
store$product_smartphone <- as.numeric(store$product_category == "Smartphone")
store$product_tv <- as.numeric(store$product_category == "TV")
store$product_laptop <- as.numeric(store$product_category == "Laptop")
store$product_tablet <- as.numeric(store$product_category == "Tablet")
```

#Export CSV
```{r}
write.csv(x = store, file = "refine_clean.csv")
```

